
name: Build ADN Systems / Eleventy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          github_token: ${{ secrets.GITHUB_TOKEN }}
